### ISSUE TITLE
default REST CA Management  should be "ignore certificate Checking"

### ISSUE THREAD

**Issue by shiramax** [matobet/moVirt#205]
when setting the connection, the default REST CA Management should be  "ignore certificate Checking"

**Comment by mykaul** [comment]
I disagree. That's the less secure option.

**Comment by jelkosz** [comment]
@shiramax I see your point, there is a small chance that the CA which is used to sign the engine certificate is already trusted by the device you are on. On the other hand falling back to the less secure option by default is not a good solution. What we do is this:
- by default we hope the CA is already trusted by the device
- if not and the connection fails due to certificate issue, we advice the user to download the engine's certificate and pre-fill the dialog with default address where the certificate is living
- and if the user explicitly decides to, he can decide to ignore the certificate checking

I think the current situation is secure while still not that user-unfriendly, so I would close this issue.

**Comment by mykaul** [comment]
@jelkosz well, could you download the certificate for the user and ask if he could trust it?

**Comment by jelkosz** [comment]
@mykaul we kinda do this - the user is redirected to the screen where everything is pre-filled and the user can decide if he wants to download this cert and trust it or not.
